const router = require('express').Router();
const auth = require('../middleware/auth');
const ctrl = require('../controllers/authController');
router.post('/register', ctrl.register);
router.post('/login', ctrl.login);
router.get('/me', auth, ctrl.me);
router.get('/verificar/:token', ctrl.verificarEmail);
router.post('/forgot-password', ctrl.forgotPassword);
router.post('/reset-password', ctrl.resetPassword);
router.post('/reenviar-verificacion', require('../middleware/auth'), ctrl.reenviarVerificacion);
module.exports = router;
